server:
  AppVersion: 1.0.0
  Port: :8000
  PprofPort: :8888
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

psql:
  IsDocker: false
  PsqlHost: localhost
  PsqlPort: 5432
  PsqlUser: postgres
  PsqlPassword:
  PsqlDbname: go_service
  PgDriver: postgres
  PsqlConnect: postgres:@(localhost:5432)/go_service

ClickHouse:
  Database: go_service
  Username: root
  Password:
  Host: localhost
#  Port: 9000
  Port: 9000

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600
